name = "hf-space-manager"
compatibility_date = "2023-04-20"

# Pages配置
pages_build_output_dir = "public"

# 开发模式 - 移除了不支持的routes配置
[dev]
port = 8788

# 环境配置
# 注意: 以下环境变量必须在Cloudflare Pages控制台中设置:
# - HF_USERNAME: 管理面板登录用户名
# - HF_PASSWORD: 管理面板登录密码
# - HF_USER: HuggingFace用户和API Token映射，格式为"username:token"，多个用户用逗号分隔，例如"user1:token1,user2:token2"
# - HF_API_TOKEN: (可选) 全局Hugging Face API令牌，当HF_USER未提供特定用户令牌时使用
# - HF_USERNAMES: (可选) 以逗号分隔的用户名列表，用于过滤Spaces，若设置了HF_USER则可以省略
# - API_KEY: (可选) 外部API访问密钥，用于第三方应用通过API调用访问和管理Spaces

# 生产环境配置
[env.production]
# KV 命名空间配置
# 请按照以下步骤设置KV命名空间:
# 1. 使用命令 `wrangler kv:namespace create SESSIONS` 创建命名空间
# 2. 从命令输出中复制生成的id和preview_id
# 3. 替换下面的 "your-kv-id-for-sessions" 和 "your-preview-kv-id-for-sessions"
kv_namespaces = [
  { binding = "SESSIONS", id = "your-kv-id-for-sessions", preview_id = "your-preview-kv-id-for-sessions" }
]

# 环境变量配置
[env.production.vars]
APP_VERSION = "1.0.0"

# 预览环境配置 (原staging环境，已重命名为符合Pages标准)
[env.preview]
# 预览环境特定配置
kv_namespaces = [
  { binding = "SESSIONS", id = "your-kv-id-for-sessions", preview_id = "your-preview-kv-id-for-sessions" }
]

[env.preview.vars]
APP_VERSION = "1.0.0"

